#Conclusie

## Beperkingen en toekomstige richtingen

Hoewel deze handleiding een breed scala aan effectgrootte- en betrouwbaarheidsintervalmethoden bestrijkt, zijn er enkele beperkingen op te merken. Ten eerste richten onze instructies zich specifiek op toepassingen in gedrags-, cognitief en sociaalwetenschappelijk onderzoek. Mogelijk moeten de technieken worden aangepast voor andere wetenschappelijke domeinen. Ten tweede behandelen we alleen vrije en open source opties, dus propriëtaire softwarepakketten worden niet besproken. Ten slotte zal de gids voortdurend moeten worden bijgewerkt naarmate er nieuwe methoden en R-pakketten verschijnen, misschien op een vergelijkbare manier als Parsons et al. (2022) Open Scholarship terms na publicatie.

In de toekomst willen we de gids uitbreiden door samen te werken met experts op andere gebieden om vakspecifieke aanbevelingen op te nemen. We zijn ook van plan om nieuwe R-pakketten en -technieken op te nemen zodra deze verschijnen. Lezers worden aangemoedigd om de documentatie van de aangehaalde pakketten en peer-reviewed bronnen te raadplegen om de beperkingen en aannames van de behandelde technieken verder te onderzoeken.

## Conclusie

Robuuste kwantificering van studieresultaten is een centrale pijler van open en reproduceerbare wetenschap. Met deze gezamenlijke verzameling van toegepaste instructies wil onze gids het berekenen van effectgroottes en betrouwbaarheidsintervallen toegankelijker maken. We hopen dat deze hulpmiddelen zowel jonge onderzoekers als ervaren wetenschappers in verschillende disciplines in staat stellen om deze cruciale statistische praktijken in hun werkproces op te nemen. Wij zijn van mening dat een meer wijdverspreide en doordachte toepassing van deze methoden de collectieve nauwkeurigheid, transparantie en impact van wetenschappelijk onderzoek enorm zal versterken.