# Definiëren van Effect Sizes

Effect sizes kwantificeren de grootte van effecten (d.w.z. de sterkte van een verband, de grootte van een verschil), die de uitkomsten zijn van ons empirisch onderzoek. Effect sizes zijn zeker geen nieuw concept. Het rapporteren ervan bleef echter jarenlang grotendeels optioneel, en pas sinds kort wordt het een standaard voor de gemeenschap: wetenschappers zien het rapporteren van effect sizes (naast de traditionele statistische significantie) nu als een must en tijdschriften beginnen deze rapportage ook verplicht te stellen. Met name in 2001 en 2010 benadrukte *The Publication Manual of the American Psychological Association*, 5e en 6e editie, dat het "bijna altijd noodzakelijk" is [@divine2018wilcoxon] om effect sizes te rapporteren [@association2010, pp. 34; zie @fritz2012, die een uitgebreide samenvatting geeft van de geschiedenis en het belang van het rapporteren van effect sizes].

Effectgroottes kunnen worden opgedeeld in brede categorieën als (1) ruwe effect sizes en (2) gestandaardiseerde effect sizes. De ruwe effect sizes zijn een samenvatting van de resultaten die worden uitgedrukt in dezelfde eenheden als de ruwe gegevens. Wanneer bijvoorbeeld kilogrammen worden gemeten, geeft een ruwe effect size een meting in kilogrammen. Neem het effect van een dieet op een behandelgroep; een controlegroep krijgt geen dieet. De verandering in gewicht kan worden uitgedrukt als het gemiddelde verschil tussen de groepen. Deze maat is ook in kg en dus een ruwe effect size. Gestandaardiseerde effect sizes uitgedrukt op een gestandaardiseerde schaal waarbij de eenheden worden uitgedrukt als standaarddeviaties (d.w.z. z-scores). Gestandaardiseerde effect sizes zijn meestal beter vergelijkbaar tussen onderzoeken die verschillende maten of eenheidsschalen gebruiken.

